<div id="contactomain">
	<div id="contacto">
		<div id="nombre">
			<div class="a">Nombre:</div>
			<div class="b"><input type="text" name="nombre" /></div>
		</div>
		<div id="email">
			<div class="a">E-Mail:</div>
			<div class="b"><input type="text" name="email" /></div>
		</div>
		<div id="telefono">
			<div class="a">Telefono:</div>
			<div class="b"><input type="text" name="telefono" /></div>
		</div>
		<div id="comentario">
			<div class="a">Comentario:</div>
		</div>
		<div>
			<textarea name="comment"></textarea>
		</div>
		<div><input id="send" type="submit" name="send" value="Enviar"/></div>
	
	
		
	</div>
</div>